# Generated by Django 4.1.3 on 2023-04-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contribution_amount',
            field=models.TextField(default=50000),
        ),
    ]
