# Generated by Django 4.1.3 on 2023-04-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0003_post_contribution_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
