# Generated by Django 4.1.3 on 2023-04-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0005_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='url',
        ),
    ]
