# Generated by Django 4.1.3 on 2023-04-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0006_rename_slug_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
