# Generated by Django 4.1.3 on 2023-04-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0009_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='post_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
