# Generated by Django 4.1.3 on 2023-04-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0010_transaction_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='donor',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
