# Generated by Django 4.1.3 on 2023-04-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0012_remove_transaction_post_id_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='post_id',
            field=models.TextField(null=True),
        ),
    ]
