# Generated by Django 4.2 on 2023-04-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0014_alter_post_contribution_amount_alter_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
