# Generated by Django 4.1.3 on 2023-04-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0016_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
