# Generated by Django 4.1.3 on 2023-04-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0017_post_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_donated',
            field=models.IntegerField(null=True),
        ),
    ]
